### ISSUE TITLE
issue: create branch automatically

### ISSUE THREAD

**Issue by kasaikou** [kasaikou/kasaikou#4]
### Abstract

Create a GitHub Actions workflow to automatically create and link a branch when an issue is created.

### Tasks

- [ ] Create GitHub Actions
  - [ ] When Issue open
  - [ ] When Issue reopen
  - [ ] When Issue close

### Tips and References

- https://cli.github.com/manual/gh_issue_develop
